### ISSUE TITLE
parallel fit?

### ISSUE THREAD

**Issue by BenoitLondon** [jchiquet/PLNmodels#15]
when fitting the PLNPCA up to 5 dimensions, it uses 10 cores. I wonder if we could use more cores inside each fit to speed up the process?

**Comment by BenoitLondon** [comment]
actually changing the default "inception" parameter to "GLM" made it super fast. But I m still not sure what is parallelized in the algorithm.

**Comment by jchiquet** [comment]
Hi Benoît,

In PLNPCA, you can modify the number of core thanks to the control.main parameters, e.g.

```r
PLNPCA(abundance ~ 1, ranks=1:5, control.main = list(cores = 5)
```

Note that is irrelevant to use a number of cores more cores greater than the ranks vector size, as the process is parallelized of of ranks.

Also, you should not change the default inception parameter: if it go superfast, it is probably because then optimization fails, surely because such an initialization brought you to a bad local optimum... I will probably remove the GLM parameter in the future.
