### ISSUE TITLE
Network reconstruction on very sparse matrices

### ISSUE THREAD

**Issue by wrshoemaker** [jchiquet/PLNmodels#17]
Hello,

I submitted a GitHub issue a few months back asking whether the `PLNnetwork()` function works on a matrix of Poisson distributed data that's been transformed so it's not an integer. That issue is closed and the function worked fine. However, I tried running `PLNnetwork()` on the matrix containing raw counts and it basically returned an identity matrix as the network, where all the values are zero except for the diagonal elements. 

The raw count matrix is **very** sparse (the majority of non-zero observations have counts of one or two). There are also only six observations. Does `PLNnetwork()` automatically remove observations with low counts, similar to how a lot of ecological analyses ignore species that are only counted once (i.e., singletons)?  

Again, thank you for building and maintaining this package and for responding to issues. I've already gotten a lot of use out of this package.

Best,
Will

**Comment by jchiquet** [comment]
Hi Will,

Thanks for your interest in PLNmodels.

Could you please specify exactly how many rows and  columns do you have in your matrix ? 

If the problem is very sparse and the sample size very low, you probably lack of power and the method choose the "empty" network because BIC/ICL like criteria (and even stability approaches) are not powerful enough to find any stable edge in your network... So that may be a statistical reason rather than a computational cause.

How do you deal with the question of model selection anyway ?

**Comment by wrshoemaker** [comment]
Hi Julien,

There are 6 rows (observations) and 231 columns (variables) in the matrix. I tried both StARS and BIC for model selection and got the same result. I was able to infer a network when I re-scaled the observations (ex. transforming a count value of 1 to 4.5) while maintaining the same number of zeros. The re-scaling procedure is for this particular type of biological data, so it isn't meaningful for any arbitrary matrix.

When I performed model selection on the re-scaled matrix I had to use BIC, since it took several days to run StARS.

**Comment by jchiquet** [comment]
Hi Will,

As I suspected, the problem is ultra high dimensional... Only 6 samples to infer a 231 * 231 matrix of covariance, that is, 231 * (231 +1 / 2) parameters ! My first advice would be to drastically reduce the number of species if you want to get a meaningful network. 

Second, I guess that when you transform the counts from 1 to 4.5, you artificially increase the signal/variance which may explain why you manage toi select a few edges in the network in this case...

Hope this helps !

**Comment by wrshoemaker** [comment]
Hi Julien,

Thank you for the response. I'm just starting to work on network reconstruction, so I appreciate you taking the time to explain the inference problem to me. It makes much more sense when the problem is viewed as inferring a covariance matrix. I'll reduce the number of species to see if I get similar results in my downstream analyses. The effect of the transformation also makes much more sense when viewed as a signal/variance problem.

I'll go ahead and close this issue.

Best,
Will
